/* ============================================================================
   CASE 4 — GEOSPATIAL | 01_setup_and_load.sql
   Load 3 tabel geo dari Git Workspace (pola flood-resilience).
   ============================================================================ */
USE ROLE ACCOUNTADMIN; USE WAREHOUSE GEN2_SMALL;
USE DATABASE AMAR_WORKSHOP_P2; USE SCHEMA GEO;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT TYPE=CSV PARSE_HEADER=TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY='"' ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;

CREATE OR REPLACE STAGE GEO_DATA_STAGE
  DIRECTORY=(ENABLE=TRUE) ENCRYPTION=(TYPE='SNOWFLAKE_SSE');

COPY FILES INTO @GEO_DATA_STAGE/
FROM 'snow://workspace/USER$.PUBLIC."amar_workshop_part_2"/versions/live/'
FILES=(
  'case4_geospatial/data/customers_geo.csv',
  'case4_geospatial/data/service_points.csv',
  'case4_geospatial/data/loan_applications_geo.csv'
);
ALTER STAGE GEO_DATA_STAGE REFRESH;

CREATE OR REPLACE TABLE CUSTOMERS_GEO (
  CUSTOMER_ID NUMBER, CITY STRING, LATITUDE FLOAT, LONGITUDE FLOAT,
  PRODUCT STRING, INCOME FLOAT, DEFAULT_FLAG NUMBER);
CREATE OR REPLACE TABLE SERVICE_POINTS (
  SERVICE_POINT_ID NUMBER, SP_TYPE STRING, CITY STRING, LATITUDE FLOAT, LONGITUDE FLOAT);
CREATE OR REPLACE TABLE LOAN_APPLICATIONS_GEO (
  APP_ID NUMBER, CUSTOMER_ID NUMBER, SUBMIT_TS TIMESTAMP_NTZ,
  LATITUDE FLOAT, LONGITUDE FLOAT, LOAN_AMOUNT FLOAT);

COPY INTO CUSTOMERS_GEO FROM @GEO_DATA_STAGE/case4_geospatial/data/customers_geo.csv
  FILE_FORMAT=CSV_FORMAT MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE ON_ERROR='CONTINUE';
COPY INTO SERVICE_POINTS FROM @GEO_DATA_STAGE/case4_geospatial/data/service_points.csv
  FILE_FORMAT=CSV_FORMAT MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE ON_ERROR='CONTINUE';
COPY INTO LOAN_APPLICATIONS_GEO FROM @GEO_DATA_STAGE/case4_geospatial/data/loan_applications_geo.csv
  FILE_FORMAT=CSV_FORMAT MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE ON_ERROR='CONTINUE';

SELECT 'customers' t, COUNT(*) n FROM CUSTOMERS_GEO
UNION ALL SELECT 'service_points', COUNT(*) FROM SERVICE_POINTS
UNION ALL SELECT 'applications', COUNT(*) FROM LOAN_APPLICATIONS_GEO;
