/* ============================================================================
   CASE 3 — REPAYMENT VINTAGE | 02_views.sql
   - VW_REPAYMENT_LONG : unpivot month_0..24 (wide) -> long (teaching point)
   - VW_PAYBACK_CURVE  : agregat payback rate per cohort (loan_paid_out month)
   Ekuivalen "Look" di Looker; dikonsumsi Streamlit & Google Sheet (SQL API).
   ============================================================================ */
USE ROLE ACCOUNTADMIN;
USE DATABASE AMAR_WORKSHOP_P2;
USE SCHEMA REPAYMENT;

CREATE OR REPLACE VIEW VW_REPAYMENT_LONG AS
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         0 AS MONTH_INDEX,
         MONTH_0_PAYMENT AS PAYMENT,
         MONTH_0_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_0_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_0_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_0_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_0_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         1 AS MONTH_INDEX,
         MONTH_1_PAYMENT AS PAYMENT,
         MONTH_1_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_1_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_1_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_1_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_1_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         2 AS MONTH_INDEX,
         MONTH_2_PAYMENT AS PAYMENT,
         MONTH_2_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_2_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_2_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_2_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_2_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         3 AS MONTH_INDEX,
         MONTH_3_PAYMENT AS PAYMENT,
         MONTH_3_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_3_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_3_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_3_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_3_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         4 AS MONTH_INDEX,
         MONTH_4_PAYMENT AS PAYMENT,
         MONTH_4_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_4_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_4_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_4_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_4_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         5 AS MONTH_INDEX,
         MONTH_5_PAYMENT AS PAYMENT,
         MONTH_5_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_5_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_5_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_5_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_5_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         6 AS MONTH_INDEX,
         MONTH_6_PAYMENT AS PAYMENT,
         MONTH_6_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_6_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_6_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_6_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_6_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         7 AS MONTH_INDEX,
         MONTH_7_PAYMENT AS PAYMENT,
         MONTH_7_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_7_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_7_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_7_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_7_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         8 AS MONTH_INDEX,
         MONTH_8_PAYMENT AS PAYMENT,
         MONTH_8_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_8_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_8_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_8_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_8_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         9 AS MONTH_INDEX,
         MONTH_9_PAYMENT AS PAYMENT,
         MONTH_9_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_9_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_9_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_9_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_9_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         10 AS MONTH_INDEX,
         MONTH_10_PAYMENT AS PAYMENT,
         MONTH_10_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_10_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_10_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_10_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_10_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         11 AS MONTH_INDEX,
         MONTH_11_PAYMENT AS PAYMENT,
         MONTH_11_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_11_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_11_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_11_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_11_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         12 AS MONTH_INDEX,
         MONTH_12_PAYMENT AS PAYMENT,
         MONTH_12_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_12_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_12_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_12_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_12_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         13 AS MONTH_INDEX,
         MONTH_13_PAYMENT AS PAYMENT,
         MONTH_13_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_13_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_13_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_13_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_13_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         14 AS MONTH_INDEX,
         MONTH_14_PAYMENT AS PAYMENT,
         MONTH_14_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_14_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_14_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_14_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_14_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         15 AS MONTH_INDEX,
         MONTH_15_PAYMENT AS PAYMENT,
         MONTH_15_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_15_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_15_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_15_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_15_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         16 AS MONTH_INDEX,
         MONTH_16_PAYMENT AS PAYMENT,
         MONTH_16_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_16_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_16_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_16_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_16_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         17 AS MONTH_INDEX,
         MONTH_17_PAYMENT AS PAYMENT,
         MONTH_17_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_17_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_17_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_17_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_17_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         18 AS MONTH_INDEX,
         MONTH_18_PAYMENT AS PAYMENT,
         MONTH_18_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_18_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_18_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_18_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_18_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         19 AS MONTH_INDEX,
         MONTH_19_PAYMENT AS PAYMENT,
         MONTH_19_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_19_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_19_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_19_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_19_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         20 AS MONTH_INDEX,
         MONTH_20_PAYMENT AS PAYMENT,
         MONTH_20_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_20_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_20_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_20_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_20_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         21 AS MONTH_INDEX,
         MONTH_21_PAYMENT AS PAYMENT,
         MONTH_21_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_21_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_21_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_21_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_21_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         22 AS MONTH_INDEX,
         MONTH_22_PAYMENT AS PAYMENT,
         MONTH_22_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_22_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_22_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_22_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_22_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         23 AS MONTH_INDEX,
         MONTH_23_PAYMENT AS PAYMENT,
         MONTH_23_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_23_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_23_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_23_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_23_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE
UNION ALL
  SELECT REF_NUM, APP_ID, LOAN_AMOUNT, LOAN_PAID_OUT_DATE, RESTRUCT_STATUS, APP_TYPE, SCORE_MODEL,
         24 AS MONTH_INDEX,
         MONTH_24_PAYMENT AS PAYMENT,
         MONTH_24_PAYMENT_CRM AS PAYMENT_CRM,
         MONTH_24_PAYMENT_BANK AS PAYMENT_BANK,
         MONTH_24_PAYMENT_CUMULATIVE AS CUMULATIVE,
         MONTH_24_PAYMENT_CUMULATIVE_CRM AS CUMULATIVE_CRM,
         MONTH_24_PAYMENT_CUMULATIVE_BANK AS CUMULATIVE_BANK
  FROM LOAN_REPAYMENT_VINTAGE;

-- Payback curve: rata-rata % pelunasan kumulatif per bulan-ke-N, per cohort
CREATE OR REPLACE VIEW VW_PAYBACK_CURVE AS
SELECT
    DATE_TRUNC('month', TO_DATE(LOAN_PAID_OUT_DATE)) AS COHORT_MONTH,
    APP_TYPE,
    MONTH_INDEX,
    COUNT(DISTINCT REF_NUM)                          AS N_LOANS,
    SUM(LOAN_AMOUNT)                                 AS TOTAL_PRINCIPAL,
    SUM(CUMULATIVE)                                  AS TOTAL_PAID,
    ROUND(SUM(CUMULATIVE)/NULLIF(SUM(LOAN_AMOUNT),0),4) AS PAYBACK_RATE
FROM VW_REPAYMENT_LONG
GROUP BY 1,2,3;

SELECT MONTH_INDEX, ROUND(AVG(PAYBACK_RATE),3) AS avg_payback
FROM VW_PAYBACK_CURVE GROUP BY 1 ORDER BY 1;
